baseURL = "https://douikb.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "terminal"

[params]
  centerTheme = true
  fullWidthTheme = false
  showMenuItems = 2
  themeColor = "green"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2